# Generated by Django 5.1.9 on 2025-08-11 10:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('adl_weatherlink_plugin', '0002_remove_weatherlinkstationlink_data_structure_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherlinkstationlink',
            name='timezone',
        ),
    ]
